export const MARITAL_STATUSES = ["SINGLE", "MARRIED", "DIVORCED", "WIDOWED", "COMMON_LAW", "SEPARATED", "OTHER"] as const;
export type MaritalStatus = typeof MARITAL_STATUSES[number];

export const EMPLOYMENT_TYPES = [
  "SALARIED", "SELF_EMPLOYED", "CONTROLLING_SHAREHOLDER", "RETIRED", "GOVERNMENT_EMPLOYEE",
  "SECURITY_FORCES", "ALLOWANCE", "UNEMPLOYED", "OTHER"
] as const;
export type EmploymentType = typeof EMPLOYMENT_TYPES[number];

export const ADDITIONAL_INCOME_TYPES = [
  "SECOND_BUSINESS", "RENTAL_INCOME", "ALLOWANCE", "ALIMONY", "PENSION", "REGULAR_OVERTIME",
  "REGULAR_BONUSES", "FOREIGN_INCOME", "INVESTMENT_INCOME", "FAMILY_SUPPORT", "OTHER"
] as const;
export type AdditionalIncomeType = typeof ADDITIONAL_INCOME_TYPES[number];

export const DEAL_TYPES = [
  "PURCHASE_FROM_CONTRACTOR", "BUYER_PRICE_PROGRAM", "SECOND_HAND_PURCHASE", "RENOVATION",
  "DEBT_CONSOLIDATION", "BUSINESS_PURPOSE", "ANY_PURPOSE", "SELF_CONSTRUCTION", "FAMILY_TRANSACTION",
  "KIBBUTZ_PURCHASE_OR_CONSTRUCTION", "RECEIVER_PURCHASE", "REVERSE_MORTGAGE", "TAMA", "MORTGAGE_REFINANCE"
] as const;
export type DealType = typeof DEAL_TYPES[number];

export const PROPERTY_TYPES = [
  "APARTMENT", "HOUSE", "SEMI_DETACHED", "GARDEN_APARTMENT", "PENTHOUSE", "LAND", "COMMERCIAL",
  "FARM", "ESTATE", "KIBBUTZ", "OTHER"
] as const;
export type PropertyType = typeof PROPERTY_TYPES[number];

export const PROPERTY_REGIONS = ["CENTER", "NORTH", "SOUTH", "JERUSALEM"] as const;
export type PropertyRegion = typeof PROPERTY_REGIONS[number];

export const BORROWER_RELATIONSHIPS = ["MARRIED", "COMMON_LAW", "FAMILY", "PARTNERS", "OTHER"] as const;
export type BorrowerRelationship = typeof BORROWER_RELATIONSHIPS[number];

export const MAX_BORROWERS = 5;
