import {useCallback, useEffect, useState, type FormEvent} from "react";
import {CalendarDays, Plus, Trash2} from "lucide-react";
import type {BusinessCalendarExceptionRecord} from "../types";
import {api} from "../utils/apiClient";

const labels = {HOLIDAY: "חג", NON_WORKING_DAY: "יום שבתון חריג", FORCED_WORKING_DAY: "יום עבודה חריג"};
export default function AdminBusinessCalendarView() {
  const [items, setItems] = useState<BusinessCalendarExceptionRecord[]>([]); const [form, setForm] = useState({date: "", type: "NON_WORKING_DAY" as BusinessCalendarExceptionRecord["type"], title: "", source: "הגדרת מנהל"}); const [error, setError] = useState("");
  const load = useCallback(async () => setItems(await api.businessCalendar()), []); useEffect(() => {void load();}, [load]);
  const submit = async (event: FormEvent) => {event.preventDefault(); setError(""); try {await api.createBusinessCalendarException(form); setForm({...form, date: "", title: ""}); await load();} catch {setError("לא ניתן לשמור את החריג. ייתכן שכבר קיימת הגדרה לתאריך זה.");}};
  return <main className="admin-page"><section className="page-title"><div><span className="eyebrow">Asia/Jerusalem</span><h1>לוח ימי עסקים בישראל</h1><p>ראשון עד חמישי הם ימי עסקים. כאן ניתן להגדיר חגים, שבתון וימי עבודה חריגים.</p></div></section>{error && <p className="form-message error">{error}</p>}<section className="calendar-admin-layout"><form className="content-card calendar-form" onSubmit={(event) => void submit(event)}><CalendarDays /><h2>חריג חדש</h2><label><span>תאריך *</span><input type="date" value={form.date} onChange={(event) => setForm({...form, date: event.target.value})} required /></label><label><span>סוג *</span><select value={form.type} onChange={(event) => setForm({...form, type: event.target.value as BusinessCalendarExceptionRecord["type"]})}><option value="HOLIDAY">חג</option><option value="NON_WORKING_DAY">יום שבתון חריג</option><option value="FORCED_WORKING_DAY">יום עבודה חריג</option></select></label><label><span>שם *</span><input value={form.title} onChange={(event) => setForm({...form, title: event.target.value})} required /></label><label><span>מקור *</span><input value={form.source} onChange={(event) => setForm({...form, source: event.target.value})} required /></label><button type="submit" className="primary-action"><Plus />הוספה</button></form><section className="content-card"><h2>חריגים מוגדרים</h2>{!items.length ? <div className="empty-state">לא הוגדרו חריגים ידניים.</div> : <div className="calendar-list">{items.map((item) => <article key={item.id}><time>{item.date}</time><div><strong>{item.title}</strong><small>{labels[item.type]} · {item.source}</small></div><button type="button" className="icon-action danger" aria-label={`מחיקת ${item.title}`} onClick={() => {if (window.confirm("למחוק את החריג?")) void api.deleteBusinessCalendarException(item.id).then(load);}}><Trash2 /></button></article>)}</div>}</section></section></main>;
}
