import {useCallback, useEffect, useState, type FormEvent} from "react";
import {Building2, Edit3, Mail, Plus, Power, Trash2, UserPlus, X} from "lucide-react";
import type {FinancingCompanyAdmin, FinancingCompanyContact} from "../types";
import {ApiError, api} from "../utils/apiClient";
import {formatDate} from "../utils/formatters";

const emptyCompany = {name: "", legalName: "", companyNumber: "", phone: "", address: "", website: "", activityAreas: "", adminNotes: "", active: false};
const emptyContact = {firstName: "", lastName: "", roleTitle: "", email: "", phone: "", isPrimary: false, active: true};

export default function AdminFinancingCompaniesView() {
  const [companies, setCompanies] = useState<FinancingCompanyAdmin[]>([]);
  const [companyForm, setCompanyForm] = useState(emptyCompany);
  const [contactForm, setContactForm] = useState(emptyContact);
  const [editing, setEditing] = useState<FinancingCompanyAdmin | null>(null);
  const [companyModalOpen, setCompanyModalOpen] = useState(false);
  const [contactCompany, setContactCompany] = useState<FinancingCompanyAdmin | null>(null);
  const [editingContact, setEditingContact] = useState<FinancingCompanyContact | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => setCompanies(await api.adminFinancingCompanies()), []);
  useEffect(() => {void load().catch(() => setError("לא ניתן לטעון את חברות המימון."));}, [load]);
  const failure = (caught: unknown) => setError(caught instanceof ApiError ? caught.publicMessage ?? "הפעולה נכשלה." : "הפעולה נכשלה.");
  const openCompany = (company?: FinancingCompanyAdmin) => {setEditing(company ?? null); setCompanyModalOpen(true); setCompanyForm(company ? {name: company.name, legalName: company.legalName ?? "", companyNumber: company.companyNumber ?? "", phone: company.phone ?? "", address: company.address ?? "", website: company.website ?? "", activityAreas: company.activityAreas.join(", "), adminNotes: company.adminNotes ?? "", active: company.active} : emptyCompany); setError("");};
  const saveCompany = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError("");
    const values = {...companyForm, legalName: companyForm.legalName || null, companyNumber: companyForm.companyNumber || null, phone: companyForm.phone || null, address: companyForm.address || null, website: companyForm.website || null, adminNotes: companyForm.adminNotes || null, activityAreas: companyForm.activityAreas.split(",").map((value) => value.trim()).filter(Boolean)};
    try {if (editing) await api.updateFinancingCompany(editing.id, values); else await api.createFinancingCompany({...values, active: false}); await load(); setCompanyModalOpen(false); setEditing(null); setCompanyForm(emptyCompany); setMessage(editing ? "פרטי החברה עודכנו." : "החברה נוצרה כלא פעילה. כעת יש להוסיף איש קשר.");}
    catch (caught) {failure(caught);} finally {setBusy(false);}
  };
  const openContact = (company: FinancingCompanyAdmin, contact?: FinancingCompanyContact) => {setContactCompany(company); setEditingContact(contact ?? null); setContactForm(contact ? {firstName: contact.firstName, lastName: contact.lastName, roleTitle: contact.roleTitle, email: contact.email, phone: contact.phone ?? "", isPrimary: contact.isPrimary, active: contact.active} : emptyContact); setError("");};
  const saveContact = async (event: FormEvent) => {
    event.preventDefault(); if (!contactCompany) return; setBusy(true); setError("");
    try {const values = {...contactForm, phone: contactForm.phone || null}; if (editingContact) await api.updateFinancingContact(contactCompany.id, editingContact.id, values); else await api.createFinancingContact(contactCompany.id, values); await load(); setContactCompany(null); setMessage(editingContact ? "איש הקשר עודכן." : "איש הקשר נוסף.");}
    catch (caught) {failure(caught);} finally {setBusy(false);}
  };
  const toggleCompany = async (company: FinancingCompanyAdmin) => {setError(""); try {await api.updateFinancingCompany(company.id, {active: !company.active}); await load();} catch (caught) {failure(caught);}};
  return <main className="admin-page"><section className="page-title"><div><span className="eyebrow">ניהול מערכת</span><h1>חברות מימון</h1><p>ניהול חברות, תחומי פעילות ואנשי קשר מורשים לקבלת תיקים.</p></div><button type="button" className="primary-action" onClick={() => openCompany()}><Plus />חברה חדשה</button></section>
    {message && <p className="form-message success" role="status">{message}</p>}{error && <p className="form-message error" role="alert">{error}</p>}
    <section className="admin-company-grid">{companies.map((company) => <article className="content-card admin-company-card" key={company.id}><header><span className="lender-logo"><Building2 /></span><div><h2>{company.name}</h2><p>{company.legalName || "שם משפטי לא הוגדר"}</p></div><span className={`status-badge ${company.active ? "status-active" : "status-draft"}`}>{company.active ? "פעילה" : "לא פעילה"}</span></header>
      <div className="company-stat-row"><span><strong>{company.submissionCount}</strong> תיקים</span><span><strong>{company.interestedCount}</strong> מעוניינת</span><span><strong>{company.notInterestedCount}</strong> לא מעוניינת</span><span><strong>{company.expiredCount}</strong> פגו</span></div>
      <p className="activity-tags">{company.activityAreas.length ? company.activityAreas.map((area) => <span key={area}>{area}</span>) : "לא הוגדרו תחומי פעילות"}</p><p>שליחה אחרונה: {company.lastSentAt ? formatDate(company.lastSentAt) : "טרם נשלח תיק"}</p>
      <section className="company-contacts"><header><h3>אנשי קשר ({company.activeContactCount} פעילים)</h3><button type="button" className="text-action" onClick={() => openContact(company)}><UserPlus />הוספה</button></header>{company.contacts.map((contact) => <article key={contact.id}><span className={contact.active ? "contact-state active" : "contact-state"} /><div><strong>{contact.firstName} {contact.lastName}{contact.isPrimary ? " · ראשי" : ""}</strong><small>{contact.roleTitle} · {contact.email}</small></div><button type="button" className="icon-action" aria-label={`עריכת ${contact.firstName}`} onClick={() => openContact(company, contact)}><Edit3 /></button><button type="button" className="icon-action danger" aria-label={`מחיקת ${contact.firstName}`} onClick={() => {if (window.confirm("למחוק את איש הקשר?")) void api.deleteFinancingContact(company.id, contact.id).then(load).catch(failure);}}><Trash2 /></button></article>)}</section>
      <footer><button type="button" className="secondary-action" onClick={() => openCompany(company)}><Edit3 />עריכה</button><label className="secondary-action logo-upload">העלאת לוגו<input type="file" accept="image/png,image/jpeg" onChange={(event) => {const file = event.target.files?.[0]; if (file) void api.uploadFinancingCompanyLogo(company.id, file).then(load).catch(failure); event.target.value = "";}} /></label><button type="button" className="secondary-action" onClick={() => void toggleCompany(company)}><Power />{company.active ? "השבתה" : "הפעלה"}</button><button type="button" className="danger-action" onClick={() => {if (window.confirm("מחיקה זו תשבית את החברה ואת אנשי הקשר. להמשיך?")) void api.deleteFinancingCompany(company.id).then(load).catch(failure);}}><Trash2 />מחיקה</button></footer>
    </article>)}</section>
    {companyModalOpen && <div className="modal-backdrop"><form className="modal content-card admin-form-modal" onSubmit={(event) => void saveCompany(event)}><header className="modal-heading"><h2>{editing ? "עריכת חברת מימון" : "חברת מימון חדשה"}</h2><button type="button" className="icon-action" aria-label="סגירה" onClick={() => {setCompanyModalOpen(false); setEditing(null); setCompanyForm(emptyCompany);}}><X /></button></header><div className="form-grid two-columns"><label><span>שם חברה *</span><input value={companyForm.name} onChange={(event) => setCompanyForm({...companyForm, name: event.target.value})} required /></label><label><span>שם משפטי</span><input value={companyForm.legalName} onChange={(event) => setCompanyForm({...companyForm, legalName: event.target.value})} /></label><label><span>מספר חברה / ח.פ.</span><input value={companyForm.companyNumber} onChange={(event) => setCompanyForm({...companyForm, companyNumber: event.target.value})} /></label><label><span>טלפון מרכזי</span><input value={companyForm.phone} onChange={(event) => setCompanyForm({...companyForm, phone: event.target.value})} /></label><label className="wide"><span>כתובת</span><input value={companyForm.address} onChange={(event) => setCompanyForm({...companyForm, address: event.target.value})} /></label><label className="wide"><span>אתר</span><input type="url" value={companyForm.website} onChange={(event) => setCompanyForm({...companyForm, website: event.target.value})} /></label><label className="wide"><span>תחומי פעילות — מופרדים בפסיקים</span><input value={companyForm.activityAreas} onChange={(event) => setCompanyForm({...companyForm, activityAreas: event.target.value})} /></label><label className="wide"><span>הערות אדמין — מוצפנות</span><textarea value={companyForm.adminNotes} onChange={(event) => setCompanyForm({...companyForm, adminNotes: event.target.value})} /></label>{editing && <label className="checkbox-label wide"><input type="checkbox" checked={companyForm.active} onChange={(event) => setCompanyForm({...companyForm, active: event.target.checked})} />חברה פעילה</label>}</div><div className="modal-actions"><button type="button" className="secondary-action" onClick={() => {setCompanyModalOpen(false); setEditing(null); setCompanyForm(emptyCompany);}}>ביטול</button><button type="submit" className="primary-action" disabled={busy}>{busy ? "שומר…" : "שמירה"}</button></div></form></div>}
    {contactCompany && <div className="modal-backdrop"><form className="modal content-card admin-form-modal" onSubmit={(event) => void saveContact(event)}><header className="modal-heading"><div><span className="eyebrow">{contactCompany.name}</span><h2>{editingContact ? "עריכת איש קשר" : "איש קשר חדש"}</h2></div><button type="button" className="icon-action" aria-label="סגירה" onClick={() => setContactCompany(null)}><X /></button></header><div className="form-grid two-columns"><label><span>שם פרטי *</span><input value={contactForm.firstName} onChange={(event) => setContactForm({...contactForm, firstName: event.target.value})} required /></label><label><span>שם משפחה *</span><input value={contactForm.lastName} onChange={(event) => setContactForm({...contactForm, lastName: event.target.value})} required /></label><label><span>תפקיד *</span><input value={contactForm.roleTitle} onChange={(event) => setContactForm({...contactForm, roleTitle: event.target.value})} required /></label><label><span>דוא״ל *</span><input type="email" value={contactForm.email} onChange={(event) => setContactForm({...contactForm, email: event.target.value})} required /></label><label><span>טלפון</span><input value={contactForm.phone} onChange={(event) => setContactForm({...contactForm, phone: event.target.value})} /></label><label className="checkbox-label"><input type="checkbox" checked={contactForm.isPrimary} onChange={(event) => setContactForm({...contactForm, isPrimary: event.target.checked})} />איש קשר ראשי</label><label className="checkbox-label"><input type="checkbox" checked={contactForm.active} onChange={(event) => setContactForm({...contactForm, active: event.target.checked})} />איש קשר פעיל</label></div><div className="modal-actions"><button type="button" className="secondary-action" onClick={() => setContactCompany(null)}>ביטול</button><button type="submit" className="primary-action" disabled={busy}><Mail />שמירה</button></div></form></div>}
  </main>;
}
