import { useCallback, useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Building2, Edit3, FileUp, Send, X } from "lucide-react";
import { useParams } from "react-router-dom";
import type { Client, ClientBorrower, ClientLiability, ClientSubmission, IdentityRequest, LoanOffer } from "../types";
import { ApiError, api } from "../utils/apiClient";
import { clientFormPayload, clientToForm, moveBorrower, resizeBorrowers, resizeChildrenAges, validateClientForm, type BorrowerFormState, type ClientFormErrors, type ClientFormState } from "../utils/clientForm";
import { calculateRemainingCommitmentPeriod } from "../utils/commitmentPeriod";
import { formatAdditionalIncomeType, formatBorrowerRelationship, formatClientStatus, formatCurrency, formatDate, formatEmploymentType, formatIdentityField, formatIdentityStatus, formatLiabilityType, formatLoanPurpose, formatMaritalStatus, formatOfferStatus, formatPropertyType, formatSubmissionStatus, maskIdentityNumber } from "../utils/formatters";
import ClientFormFields from "./ClientFormFields";
import DocumentManager from "./DocumentManager";
import LoanArena from "./LoanArena";

const tabs = ["תקציר", "פרטים אישיים", "הכנסות", "התחייבויות", "נכס", "פירוט עסקה", "מסמכים", "בקשות חשיפה", "הצעות", "פעילות"] as const;
type Tab = typeof tabs[number];

export default function ClientDetailView() {
  const {id = ""} = useParams(); const clientId = Number(id);
  const [client, setClient] = useState<Client | null>(null); const [tab, setTab] = useState<Tab>("תקציר");
  const [submissions, setSubmissions] = useState<ClientSubmission[]>([]); const [offers, setOffers] = useState<LoanOffer[]>([]);
  const [identityRequests, setIdentityRequests] = useState<IdentityRequest[]>([]); const [identitySelections, setIdentitySelections] = useState<Record<number, string[]>>({});
  const [editing, setEditing] = useState(false); const [editStep, setEditStep] = useState<1 | 2 | 3>(1); const [editForm, setEditForm] = useState<ClientFormState | null>(null); const [editErrors, setEditErrors] = useState<ClientFormErrors>({}); const [saving, setSaving] = useState(false);
  const [sendOpen, setSendOpen] = useState(false); const [toast, setToast] = useState<{type: "success" | "error"; text: string; requestId?: string} | null>(null);
  const load = useCallback(async () => { const [clientResult, submissionResult, offerResult, requestResult] = await Promise.all([api.client(clientId), api.submissions(clientId), api.offers(clientId), api.identityRequests()]); setClient(clientResult); setSubmissions(submissionResult); setOffers(offerResult); const clientRequests = requestResult.filter((request) => request.clientId === clientId); setIdentityRequests(clientRequests); setIdentitySelections((current) => Object.fromEntries(clientRequests.map((request) => [request.id, current[request.id] ?? request.approvedFields ?? []]))); }, [clientId]);
  useEffect(() => { if (clientId) void load(); }, [clientId, load]);
  if (!client) return <main className="advisor-page"><div className="empty-state">טוען את תיק הלקוח…</div></main>;

  const info = (label: string, value: ReactNode) => <div className="info-row"><dt>{label}</dt><dd>{value === "" || value === null || value === undefined ? "לא צוין" : value}</dd></div>;
  const liabilitySummary = (items: ClientLiability[]) => ({balance: items.reduce((sum, item) => sum + item.currentBalance, 0), monthly: items.reduce((sum, item) => sum + item.monthlyPayment, 0), count: items.length});
  const liabilityList = (title: string, items: ClientLiability[], note?: string) => { const summary = liabilitySummary(items); return <article className="borrower-detail-card liability-detail-group" key={title}><header><div><span className="eyebrow">התחייבויות</span><h3>{title}</h3>{note && <p>{note}</p>}</div></header>{items.length === 0 ? <p className="empty-inline">אין התחייבויות פעילות.</p> : <div className="liability-detail-list">{items.map((liability) => <article className="liability-card" key={liability.id}>{liability.incompleteLegacy && <p className="form-message error">נדרש להשלים את פרטי ההתחייבות שהועברו מהמערכת הישנה.</p>}<dl className="detail-grid">{info("סוג", formatLiabilityType(liability.type))}{liability.otherTypeDescription && info("שם הגוף או סוג ההתחייבות", liability.otherTypeDescription)}{info("יתרה", formatCurrency(liability.currentBalance))}{info("החזר חודשי", formatCurrency(liability.monthlyPayment))}{info("תאריך סיום", formatDate(liability.endDate))}{info("תקופה שנותרה", liability.endDate ? calculateRemainingCommitmentPeriod(liability.endDate)?.label ?? "נדרש להשלים" : "נדרש להשלים")}{info("הערות", liability.notes || "נדרש להשלים")}</dl></article>)}</div>}<div className="form-calculation"><span>סך יתרות: <strong>{formatCurrency(summary.balance)}</strong></span><span>סך החזרים: <strong>{formatCurrency(summary.monthly)}</strong></span><span>מספר התחייבויות: <strong>{summary.count}</strong></span></div></article>; };
  const borrowerCard = (borrower: ClientBorrower, content: "personal" | "income") => <article className="borrower-detail-card" key={borrower.id}><header><div><span className="eyebrow">{borrower.isPrimary ? "לווה ראשי" : `לווה ${borrower.borrowerOrder}`}</span><h3>{borrower.firstName} {borrower.lastName}</h3></div><span className="age-badge">גיל {borrower.age ?? "—"}</span></header>{content === "personal" ? <dl className="detail-grid">{info("מספר תעודת זהות", maskIdentityNumber(borrower.identityNumber))}{info("תאריך לידה", formatDate(borrower.birthDate))}{info("טלפון", borrower.phone)}{info("דוא״ל", borrower.email)}{info("כתובת מגורים", borrower.address)}{info("מצב משפחתי", formatMaritalStatus(borrower.maritalStatus))}{info("מספר ילדים", borrower.children.numberOfChildren)}{info("גילאי הילדים", borrower.children.childrenAges.length ? borrower.children.childrenAges.join(", ") : "אין ילדים")}</dl> : <dl className="detail-grid">{info("סוג תעסוקה", formatEmploymentType(borrower.employment.employmentType))}{info("שם המעסיק או העסק", borrower.employment.employerName)}{info("תפקיד", borrower.employment.jobTitle)}{info("ותק", `${borrower.employment.employmentSeniorityYears} שנים`)}{info("הכנסה חודשית נטו", formatCurrency(borrower.income.monthlyNetIncome))}{info("האם קיימת הכנסה נוספת", borrower.income.hasAdditionalIncome ? "כן" : "לא")}{borrower.income.hasAdditionalIncome && info("סוג הכנסה נוספת", formatAdditionalIncomeType(borrower.income.additionalIncomeType))}{borrower.income.hasAdditionalIncome && info("סכום הכנסה נוספת", formatCurrency(borrower.income.additionalIncomeAmount))}{info("סך הכנסה ללווה", formatCurrency(borrower.income.monthlyNetIncome + borrower.income.additionalIncomeAmount))}</dl>}</article>;

  const openEditor = () => { setToast(null); setEditForm(clientToForm(client)); setEditErrors({}); setEditStep(1); setEditing(true); };
  const clearEditError = (key: string) => setEditErrors((current) => { const next = {...current}; Object.keys(next).filter((item) => item === key || item.startsWith(`${key}.`)).forEach((item) => delete next[item]); return next; });
  const changeEdit = <Key extends keyof ClientFormState>(key: Key, value: ClientFormState[Key]) => { if (key === "numberOfBorrowers" && editForm && Number(value) < Number(editForm.numberOfBorrowers) && !window.confirm("הקטנת מספר הלווים תסיר את הלווה האחרון לאחר השמירה. להמשיך?")) return; if (key === "borrowerRelationship" && editForm?.borrowerRelationship && editForm.borrowerRelationship !== value && !window.confirm("שינוי הקשר ישנה את אופן הצגת נתוני הילדים וההתחייבויות. להמשיך?")) return; setEditForm((current) => { if (!current) return current; if (key === "numberOfBorrowers") { const count = value as string; return {...current, numberOfBorrowers: count, borrowers: resizeBorrowers(current.borrowers, count), borrowerRelationship: Number(count) > 1 ? current.borrowerRelationship : "", borrowerRelationshipOther: Number(count) > 1 ? current.borrowerRelationshipOther : ""}; } if (key === "householdNumberOfChildren") { const count = value as string; return {...current, householdNumberOfChildren: count, householdChildrenAges: resizeChildrenAges(current.householdChildrenAges, count)}; } if (key === "borrowerRelationship") { const relationship = value as string; if (relationship === "MARRIED") return {...current, borrowerRelationship: relationship, householdLiabilities: current.householdLiabilities.length ? current.householdLiabilities : current.borrowers.flatMap((borrower) => borrower.liabilities), borrowers: current.borrowers.map((borrower) => ({...borrower, liabilities: []}))}; if (current.borrowerRelationship === "MARRIED") return {...current, borrowerRelationship: relationship, householdLiabilities: [], borrowers: current.borrowers.map((borrower, index) => ({...borrower, liabilities: index === 0 ? [...borrower.liabilities, ...current.householdLiabilities] : borrower.liabilities}))}; } return {...current, [key]: value}; }); clearEditError(String(key)); };
  const changeEditBorrower = <Key extends keyof BorrowerFormState>(index: number, key: Key, value: BorrowerFormState[Key]) => { setEditForm((current) => { if (!current) return current; const borrowers = [...current.borrowers]; const borrower = {...borrowers[index]}; if (key === "numberOfChildren") { const count = value as string; borrower.numberOfChildren = count; borrower.childrenAges = resizeChildrenAges(borrower.childrenAges, count); } else if (key === "hasAdditionalIncome" && value === "no") { borrower.hasAdditionalIncome = "no"; borrower.additionalIncomeType = ""; borrower.additionalIncomeAmount = ""; borrower.additionalIncomeDescription = ""; } else borrower[key] = value; borrowers[index] = borrower; return {...current, borrowers}; }); clearEditError(`borrowers.${index}.${String(key)}`); };
  const saveEdit = async () => { if (!editForm) return; const errors = validateClientForm(editForm); setEditErrors(errors); if (Object.keys(errors).length) { setToast({type: "error", text: "יש לתקן את השדות המסומנים לפני השמירה."}); return; } setSaving(true); try { const updated = await api.updateClient(client.id, clientFormPayload(editForm)); setClient(updated); setEditing(false); setToast({type: "success", text: "פרטי הלקוח נשמרו בהצלחה."}); } catch (caught) { setToast({type: "error", text: "שמירת פרטי הלקוח נכשלה.", requestId: caught instanceof ApiError ? caught.requestId : undefined}); } finally { setSaving(false); } };
  const latestSubmission = submissions[0];
  return <main className="advisor-page client-detail-page">{toast && <div className={`toast ${toast.type}`} role="status"><strong>{toast.text}</strong>{toast.requestId && <small>מזהה בקשה: {toast.requestId}</small>}</div>}
    <section className="client-profile-header content-card"><div className="client-profile-title"><span className="client-avatar large">{client.firstName[0]}{client.lastName[0]}</span><div><span className="eyebrow">תיק {client.publicCaseNumber}</span><h1>{client.firstName} {client.lastName}{client.numberOfBorrowers > 1 && ` ועוד ${client.numberOfBorrowers - 1}`}</h1><span className={`status-badge status-${client.status.toLowerCase()}`}>{formatClientStatus(client.status)}</span>{client.missingRequiredDocumentCount > 0 && <span className="status-badge status-warning">בתיק חסרים מסמכי חובה · {client.missingRequiredDocumentCount}</span>}</div></div><div className="client-profile-metrics"><div><small>סכום מבוקש</small><strong>{formatCurrency(client.requestedAmount)}</strong></div><div><small>שווי הנכס</small><strong>{formatCurrency(client.propertyValue)}</strong></div><div><small>התחייבויות פעילות</small><strong>{client.activeLiabilityCount}</strong></div></div><div className="profile-actions"><button type="button" className="secondary-action" onClick={openEditor}><Edit3 size={17} />עריכה</button><button type="button" className="secondary-action" onClick={() => setTab("מסמכים")}><FileUp size={17} />העלאת מסמך</button><button type="button" className="primary-action" onClick={() => setSendOpen(true)}><Send size={17} />שליחה לחברות מימון{client.missingRequiredDocumentCount > 0 && <b className="missing-count">{client.missingRequiredDocumentCount}</b>}</button></div></section>
    <nav className="client-tabs" aria-label="כרטיסיות תיק לקוח">{tabs.map((item) => <button type="button" className={tab === item ? "active" : ""} aria-current={tab === item ? "page" : undefined} key={item} onClick={() => setTab(item)}>{item}</button>)}</nav>
    <section className="content-card tab-content">
      {tab === "תקציר" && <div className="summary-grid"><article><h2>תמונת מצב</h2><dl>{info("סטטוס התיק", formatClientStatus(client.status))}{info("מספר לווים", client.numberOfBorrowers)}{info("הקשר בין הלווים", formatBorrowerRelationship(client.borrowerRelationship))}{info("מטרת ההלוואה", formatLoanPurpose(client.loanPurpose))}{info("סטטוס מול חברות", formatSubmissionStatus(latestSubmission?.status ?? null))}{info("מספר הצעות", offers.length)}{info("עודכן לאחרונה", formatDate(client.updatedAt))}</dl></article><article><h2>נתונים פיננסיים</h2><dl>{info("סך הכנסה חודשית", formatCurrency(client.totalMonthlyIncome))}{info("סך יתרות התחייבויות", formatCurrency(client.totalLiabilityBalance))}{info("סך החזרים חודשיים", formatCurrency(client.totalMonthlyPayments))}{info("מספר התחייבויות", client.activeLiabilityCount)}</dl>{client.missingRequiredDocumentCount > 0 && <button type="button" className="document-alert" onClick={() => setTab("מסמכים")}>בתיק חסרים מסמכי חובה <b>{client.missingRequiredDocumentCount}</b></button>}</article></div>}
      {tab === "פרטים אישיים" && <div className="detail-section"><h2>פרטים אישיים</h2>{client.household.numberOfChildren > 0 && <article className="borrower-detail-card household-card"><h3>נתוני משק הבית</h3><dl className="detail-grid">{info("מספר ילדים", client.household.numberOfChildren)}{info("גילאי הילדים", client.household.childrenAges.join(", "))}</dl></article>}<div className="borrower-detail-list">{client.borrowers.map((borrower) => borrowerCard(borrower, "personal"))}</div></div>}
      {tab === "הכנסות" && <div className="detail-section"><h2>הכנסות ותעסוקה</h2><div className="borrower-detail-list">{client.borrowers.map((borrower) => borrowerCard(borrower, "income"))}</div><div className="aggregate-summary">סך הכנסה חודשית לכל הלווים: <strong>{formatCurrency(client.totalMonthlyIncome)}</strong></div></div>}
      {tab === "התחייבויות" && <div className="detail-section"><h2>התחייבויות</h2><div className="borrower-detail-list">{client.borrowerRelationship === "MARRIED" ? liabilityList("התחייבויות משותפות למשק הבית", client.householdLiabilities) : client.borrowers.map((borrower) => liabilityList(`התחייבויות — לווה ${borrower.borrowerOrder}`, borrower.liabilities))}</div><div className="aggregate-summary">סך יתרות: <strong>{formatCurrency(client.totalLiabilityBalance)}</strong> · סך החזרים חודשיים: <strong>{formatCurrency(client.totalMonthlyPayments)}</strong> · מספר התחייבויות: <strong>{client.activeLiabilityCount}</strong></div></div>}
      {tab === "נכס" && <div className="detail-section"><h2>נכס ובקשת מימון</h2><dl className="detail-grid">{info("סוג הנכס", formatPropertyType(client.propertyType))}{client.propertyTypeOtherDescription && info("תיאור סוג הנכס", client.propertyTypeOtherDescription)}{info("עיר", client.propertyCity)}{info("כתובת הנכס", client.propertyAddress)}{info("שווי הנכס", formatCurrency(client.propertyValue))}{info("סכום המימון המבוקש", formatCurrency(client.requestedAmount))}</dl></div>}
      {tab === "פירוט עסקה" && <div className="detail-section"><div className="section-heading compact"><div><h2>פירוט עסקה</h2><p>מידע זה אינו נכלל בתיק האנונימי ללא אישור מפורש.</p></div><button type="button" className="secondary-action" onClick={openEditor}><Edit3 size={17} />עריכה</button></div><dl className="detail-grid">{info("מטרת ההלוואה", formatLoanPurpose(client.loanPurpose))}{info("עודכן לאחרונה", formatDate(client.dealDetailsUpdatedAt))}{info("עודכן על ידי", client.dealDetailsUpdatedBy)}</dl><div className="deal-details-text">{client.dealDetails}</div></div>}
      {tab === "מסמכים" && <DocumentManager clientId={client.id} borrowers={client.borrowers} onUpdated={() => void load()} />}
      {tab === "בקשות חשיפה" && <div className="detail-section"><h2>בקשות חשיפת זהות</h2>{identityRequests.length === 0 ? <div className="empty-state">אין בקשות חשיפה בתיק זה.</div> : <div className="request-list">{identityRequests.map((request) => { const selected = identitySelections[request.id] ?? []; return <article className="request-card" key={request.id}><h3>{request.lenderName ?? "חברת מימון"}</h3><p>{request.reason}</p><span>{formatIdentityStatus(request.status)}</span>{request.status === "PENDING" && <><fieldset><legend>בחירת פרטים לחשיפה</legend>{request.requestedFields.map((field) => <label key={field}><input type="checkbox" checked={selected.includes(field)} onChange={(event) => setIdentitySelections((current) => ({...current, [request.id]: event.target.checked ? [...selected, field] : selected.filter((item) => item !== field)}))} />{formatIdentityField(field)}</label>)}</fieldset><button type="button" className="primary-action" disabled={!selected.length} onClick={() => void api.decideIdentity(request.id, true, selected, []).then(load)}>אישור השדות שנבחרו</button></>}</article>; })}</div>}</div>}
      {tab === "הצעות" && <div className="detail-section"><h2>הצעות מימון</h2>{offers.length === 0 ? <div className="empty-state">עדיין לא התקבלו הצעות לתיק זה.</div> : <div className="offers-grid">{offers.map((offer) => <article className="offer-card" key={offer.id}><span className="stat-icon green"><Building2 /></span><h3>{offer.lenderName}</h3><span>{formatOfferStatus(offer.status)}</span><strong>{formatCurrency(offer.amount)}</strong></article>)}</div>}</div>}
      {tab === "פעילות" && <div className="detail-section"><h2>פעילות אחרונה</h2><div className="timeline"><article><span /><div><strong>התיק עודכן</strong><p>{formatDate(client.updatedAt)}</p></div></article>{submissions.map((submission) => <article key={submission.id}><span /><div><strong>{submission.lenderName}</strong><p>{formatSubmissionStatus(submission.status)} · {formatDate(submission.updatedAt)}</p></div></article>)}</div></div>}
    </section>
    {sendOpen && <div className="modal-backdrop"><section className="modal send-client-modal content-card" role="dialog" aria-modal="true" aria-label="שליחה לחברות מימון"><header className="modal-heading"><h2>שליחה לחברות מימון</h2><button type="button" className="icon-action" aria-label="סגירה" onClick={() => setSendOpen(false)}><X /></button></header><LoanArena clientId={client.id} onMissingDocuments={() => {setSendOpen(false); setTab("מסמכים");}} /></section></div>}
    {editing && editForm && <div className="modal-backdrop"><section className="modal client-edit-modal content-card" role="dialog" aria-modal="true"><header className="modal-heading"><div><span className="eyebrow">שלב {editStep} מתוך 3</span><h2>עריכת תיק לקוח</h2></div><button type="button" className="icon-action" aria-label="סגירת חלון עריכה" onClick={() => setEditing(false)}><X /></button></header><ClientFormFields form={editForm} errors={editErrors} step={editStep} onChange={changeEdit} onBorrowerChange={changeEditBorrower} onMoveBorrower={(from, to) => setEditForm((current) => current ? {...current, borrowers: moveBorrower(current.borrowers, from, to)} : current)} /><div className="modal-actions"><button type="button" className="ghost-action" onClick={() => setEditing(false)}>ביטול</button>{editStep > 1 && <button type="button" className="secondary-action" onClick={() => {setEditErrors({}); setEditStep((current) => current - 1 as 1 | 2);}}><ArrowRight size={17} />הקודם</button>}{editStep < 3 ? <button type="button" className="primary-action" onClick={() => {const errors = validateClientForm(editForm, editStep); setEditErrors(errors); if (!Object.keys(errors).length) setEditStep((current) => current + 1 as 2 | 3);}}>הבא<ArrowLeft size={17} /></button> : <button type="button" className="primary-action" disabled={saving} onClick={() => void saveEdit()}>{saving ? "שומר…" : "שמירת שינויים"}</button>}</div></section></div>}
  </main>;
}
