import type { KeyboardEvent } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import type { BorrowerFormState, ClientEditSection, ClientFormErrors, ClientFormState, LiabilityFormState } from "../utils/clientForm";
import { additionalIncomeTypeOptions, borrowerRelationshipOptions, emptyAdditionalIncomeForm, emptyLiabilityForm, employmentTypeOptions, isNonNegativeDecimalInput, isNonNegativeIntegerInput, isSharedHousehold, liabilityTypeOptions, loanPurposeOptions, maritalStatusOptions, propertyTypeOptions, usesHouseholdLiabilities } from "../utils/clientForm";
import { calculateAge } from "../utils/age";
import { calculateRemainingCommitmentPeriod } from "../utils/commitmentPeriod";
import { formatCurrency, formatEmploymentType, formatMaritalStatus } from "../utils/formatters";

interface Props {
  form: ClientFormState; errors: ClientFormErrors; step: 1 | 2 | 3;
  onChange: <Key extends keyof ClientFormState>(key: Key, value: ClientFormState[Key]) => void;
  onBorrowerChange: <Key extends keyof BorrowerFormState>(index: number, key: Key, value: BorrowerFormState[Key]) => void;
  onMoveBorrower?: (from: number, to: number) => void;
  section?: ClientEditSection;
}

const requiredMark = <b className="required-mark" aria-hidden="true">*</b>;
const integerBorrowerFields = new Set<keyof BorrowerFormState>(["numberOfChildren", "employmentSeniorityYears"]);
const integerGlobalFields = new Set<keyof ClientFormState>(["numberOfBorrowers", "householdNumberOfChildren"]);
const preventInvalidNumericKey = (event: KeyboardEvent<HTMLInputElement>, integer: boolean) => {
  if (["e", "E", "+", "-"].includes(event.key) || (integer && [".", ","].includes(event.key))) event.preventDefault();
};

export default function ClientFormFields({form, errors, step, onChange, onBorrowerChange, onMoveBorrower, section}: Props) {
  const input = (index: number, key: keyof BorrowerFormState, label: string, placeholder: string, type = "text") => {
    const integer = integerBorrowerFields.has(key);
    return <label className="form-field"><span>{label}{requiredMark}</span><input type={type} min={type === "number" ? 0 : undefined} step={type === "number" ? integer ? 1 : 0.01 : undefined} inputMode={type === "number" ? integer ? "numeric" : "decimal" : undefined} aria-label={`${label} - לווה ${index + 1}`} placeholder={placeholder} value={String(form.borrowers[index][key] ?? "")} onKeyDown={type === "number" ? (event) => preventInvalidNumericKey(event, integer) : undefined} onChange={(event) => { if (type === "number" && !(integer ? isNonNegativeIntegerInput(event.target.value) : isNonNegativeDecimalInput(event.target.value))) return; onBorrowerChange(index, key, event.target.value as never); }} aria-invalid={Boolean(errors[`borrowers.${index}.${String(key)}`])} />{errors[`borrowers.${index}.${String(key)}`] && <em role="alert">{errors[`borrowers.${index}.${String(key)}`]}</em>}</label>;
  };
  const select = (index: number, key: keyof BorrowerFormState, label: string, options: readonly (readonly [string, string])[]) => {
    const current = String(form.borrowers[index][key] ?? "");
    const legacyLabel = current && !options.some(([value]) => value === current)
      ? key === "maritalStatus" ? formatMaritalStatus(current) : formatEmploymentType(current)
      : null;
    return <label className="form-field"><span>{label}{requiredMark}</span><select aria-label={`${label} - לווה ${index + 1}`} value={current} onChange={(event) => onBorrowerChange(index, key, event.target.value as never)} aria-invalid={Boolean(errors[`borrowers.${index}.${String(key)}`])}><option value="">בחירה</option>{legacyLabel && <option value={current}>{legacyLabel}</option>}{options.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select>{errors[`borrowers.${index}.${String(key)}`] && <em role="alert">{errors[`borrowers.${index}.${String(key)}`]}</em>}</label>;
  };
  const globalInput = (key: keyof ClientFormState, label: string, placeholder: string, type = "text") => {
    const integer = integerGlobalFields.has(key);
    return <label className="form-field"><span>{label}{requiredMark}</span><input type={type} min={type === "number" ? key === "numberOfBorrowers" ? 1 : 0 : undefined} step={type === "number" ? integer ? 1 : 0.01 : undefined} inputMode={type === "number" ? integer ? "numeric" : "decimal" : undefined} aria-label={label} placeholder={placeholder} value={String(form[key] ?? "")} onKeyDown={type === "number" ? (event) => preventInvalidNumericKey(event, integer) : undefined} onChange={(event) => { if (type === "number" && !(integer ? isNonNegativeIntegerInput(event.target.value) : isNonNegativeDecimalInput(event.target.value))) return; onChange(key, event.target.value as never); }} aria-invalid={Boolean(errors[String(key)])} />{errors[String(key)] && <em role="alert">{errors[String(key)]}</em>}</label>;
  };
  const globalSelect = (key: keyof ClientFormState, label: string, options: readonly (readonly [string, string])[]) => <label className="form-field"><span>{label}{requiredMark}</span><select aria-label={label} value={String(form[key] ?? "")} onChange={(event) => onChange(key, event.target.value as never)} aria-invalid={Boolean(errors[String(key)])}><option value="">בחירה</option>{options.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select>{errors[String(key)] && <em role="alert">{errors[String(key)]}</em>}</label>;

  const liabilitiesEditor = (title: string, liabilities: LiabilityFormState[], prefix: string, change: (next: LiabilityFormState[]) => void, message?: string) => <section className="liabilities-editor borrower-card">
    <div className="borrower-card-heading"><div><span className="eyebrow">התחייבויות</span><h3>{title}</h3>{message && <p>{message}</p>}</div><button type="button" className="secondary-action" onClick={() => change([...liabilities, emptyLiabilityForm()])}><Plus size={17} />הוספת התחייבות</button></div>
    {liabilities.length === 0 ? <p className="empty-inline">לא נוספו התחייבויות.</p> : liabilities.map((liability, liabilityIndex) => {
      const key = `${prefix}.${liabilityIndex}`;
      const update = (field: keyof LiabilityFormState, value: string) => change(liabilities.map((item, index) => index === liabilityIndex ? {...item, [field]: value, incompleteLegacy: false} : item));
      const updateType = (type: string) => change(liabilities.map((item, index) => index === liabilityIndex ? {...item, type, currentBalance: type === "ALIMONY" || type === "RENT" ? "" : item.currentBalance, financialInstitution: type === "LOAN" || type === "MORTGAGE" ? item.financialInstitution ?? "" : "", incompleteLegacy: false} : item));
      const period = calculateRemainingCommitmentPeriod(liability.endDate);
      return <article className="liability-card" key={liability.id ?? liabilityIndex}>
        <header><h4>התחייבות {liabilityIndex + 1}</h4><button type="button" className="icon-text-button danger" onClick={() => change(liabilities.filter((_, index) => index !== liabilityIndex))}><Trash2 size={16} />מחיקה</button></header>
        {liability.incompleteLegacy && <p className="form-message error">נדרש להשלים את פרטי ההתחייבות שהועברו מהמערכת הישנה.</p>}
        <div className="responsive-form-grid">
          <label className="form-field"><span>סוג התחייבות{requiredMark}</span><select aria-label={`סוג התחייבות ${liabilityIndex + 1}`} value={liability.type} onChange={(event) => updateType(event.target.value)}><option value="">בחירה</option>{liabilityTypeOptions.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select>{errors[`${key}.type`] && <em role="alert">{errors[`${key}.type`]}</em>}</label>
          {liability.type === "OTHER_FINANCIAL_ENTITY" && <label className="form-field"><span>שם הגוף או סוג ההתחייבות{requiredMark}</span><input value={liability.otherTypeDescription} onChange={(event) => update("otherTypeDescription", event.target.value)} />{errors[`${key}.otherTypeDescription`] && <em role="alert">{errors[`${key}.otherTypeDescription`]}</em>}</label>}
          {(liability.type === "LOAN" || liability.type === "MORTGAGE") && <label className="form-field"><span>הגוף הפיננסי{requiredMark}</span><input value={liability.financialInstitution ?? ""} onChange={(event) => update("financialInstitution", event.target.value)} placeholder="לדוגמה: בנק הפועלים, מזרחי טפחות, MAX, ישראכרט..." />{errors[`${key}.financialInstitution`] && <em role="alert">{errors[`${key}.financialInstitution`]}</em>}</label>}
          {liability.type !== "ALIMONY" && liability.type !== "RENT" && <label className="form-field"><span>יתרה נוכחית{requiredMark}</span><input type="number" min="0" step="0.01" inputMode="decimal" value={liability.currentBalance} onKeyDown={(event) => preventInvalidNumericKey(event, false)} onChange={(event) => { if (isNonNegativeDecimalInput(event.target.value)) update("currentBalance", event.target.value); }} placeholder="הזן סכום בש״ח" />{errors[`${key}.currentBalance`] && <em role="alert">{errors[`${key}.currentBalance`]}</em>}</label>}
          <label className="form-field"><span>החזר חודשי{requiredMark}</span><input type="number" min="0" step="0.01" inputMode="decimal" value={liability.monthlyPayment} onKeyDown={(event) => preventInvalidNumericKey(event, false)} onChange={(event) => { if (isNonNegativeDecimalInput(event.target.value)) update("monthlyPayment", event.target.value); }} placeholder="הזן סכום בש״ח" />{errors[`${key}.monthlyPayment`] && <em role="alert">{errors[`${key}.monthlyPayment`]}</em>}</label>
          <label className="form-field"><span>תאריך סיום התחייבות{requiredMark}</span><input type="date" value={liability.endDate} onChange={(event) => update("endDate", event.target.value)} />{errors[`${key}.endDate`] && <em role="alert">{errors[`${key}.endDate`]}</em>}</label>
          <label className="form-field"><span>תקופה שנותרה</span><input readOnly value={period?.label ?? "יש להזין תאריך עתידי"} /></label>
          <label className="form-field form-field-wide"><span>הערות{requiredMark}</span><textarea rows={3} maxLength={1000} value={liability.notes} onChange={(event) => update("notes", event.target.value)} placeholder="פרטים חשובים על ההתחייבות" />{errors[`${key}.notes`] && <em role="alert">{errors[`${key}.notes`]}</em>}</label>
        </div>
      </article>;
    })}
    <div className="form-calculation"><span>סך יתרות: <strong>{formatCurrency(liabilities.reduce((sum, item) => sum + Number(item.currentBalance || 0), 0))}</strong></span><span>סך החזרים חודשיים: <strong>{formatCurrency(liabilities.reduce((sum, item) => sum + Number(item.monthlyPayment || 0), 0))}</strong></span><span>מספר התחייבויות: <strong>{liabilities.length}</strong></span></div>
  </section>;

  if (section === "personal" || (!section && step === 1)) return <fieldset><legend>פרטים אישיים</legend><div className="responsive-form-grid">{globalInput("numberOfBorrowers", "מספר לווים בתיק", "1", "number")}{Number(form.numberOfBorrowers) > 1 && globalSelect("borrowerRelationship", "מה הקשר בין הלווים?", borrowerRelationshipOptions)}{form.borrowerRelationship === "OTHER" && globalInput("borrowerRelationshipOther", "תיאור הקשר בין הלווים", "פרט את הקשר")}</div>
    {isSharedHousehold(form.borrowerRelationship) && <section className="borrower-card household-card"><h3>נתוני משק הבית</h3><div className="responsive-form-grid">{globalInput("householdNumberOfChildren", "מספר ילדים", "0", "number")}{form.householdChildrenAges.map((age, index) => <label className="form-field" key={index}><span>ילד {index + 1} — גיל{requiredMark}</span><input type="number" min="0" step="1" inputMode="numeric" value={age} onKeyDown={(event) => preventInvalidNumericKey(event, true)} onChange={(event) => { if (isNonNegativeIntegerInput(event.target.value)) onChange("householdChildrenAges", form.householdChildrenAges.map((item, ageIndex) => ageIndex === index ? event.target.value : item)); }} /></label>)}</div></section>}
    <div className="borrower-stack">{form.borrowers.map((borrower, index) => <section className="borrower-card" key={index}><div className="borrower-card-heading"><div><span className="eyebrow">{index === 0 ? "לווה ראשי" : "לווה נוסף"}</span><h3>פרטי לווה {index + 1}</h3></div>{onMoveBorrower && form.borrowers.length > 1 && <div>{index > 0 && <button type="button" className="icon-action" aria-label="העברת לווה למעלה" onClick={() => onMoveBorrower(index, index - 1)}><ArrowUp /></button>}{index < form.borrowers.length - 1 && <button type="button" className="icon-action" aria-label="העברת לווה למטה" onClick={() => onMoveBorrower(index, index + 1)}><ArrowDown /></button>}</div>}</div><div className="responsive-form-grid">{input(index, "firstName", "שם פרטי", "הקלד את שם הלקוח")}{input(index, "lastName", "שם משפחה", "הקלד שם משפחה")}{input(index, "identityNumber", "מספר תעודת זהות", "9 ספרות ללא מקפים")}{input(index, "birthDate", "תאריך לידה", "", "date")}<label className="form-field"><span>גיל מחושב</span><input readOnly value={calculateAge(borrower.birthDate) ?? ""} /></label>{input(index, "phone", "טלפון", "050-0000000", "tel")}{input(index, "email", "דוא״ל", "name@example.com", "email")}{(form.borrowerRelationship !== "MARRIED" || index === 0) && input(index, "address", "כתובת מגורים", "רחוב, מספר ועיר")}{form.borrowerRelationship === "MARRIED" && index > 0 && <p className="form-field derived-field-message">כתובת המגורים זהה לכתובת של לווה 1</p>}{form.borrowerRelationship !== "MARRIED" && select(index, "maritalStatus", "מצב משפחתי", maritalStatusOptions)}{!isSharedHousehold(form.borrowerRelationship) && input(index, "numberOfChildren", "מספר ילדים", "0", "number")}{!isSharedHousehold(form.borrowerRelationship) && borrower.childrenAges.map((age, childIndex) => <label className="form-field" key={childIndex}><span>ילד {childIndex + 1} — גיל{requiredMark}</span><input type="number" min="0" step="1" inputMode="numeric" value={age} onKeyDown={(event) => preventInvalidNumericKey(event, true)} onChange={(event) => { if (isNonNegativeIntegerInput(event.target.value)) onBorrowerChange(index, "childrenAges", borrower.childrenAges.map((item, ageIndex) => ageIndex === childIndex ? event.target.value : item)); }} /></label>)}</div></section>)}</div></fieldset>;

  if (section === "income" || section === "liabilities" || (!section && step === 2)) {
    const showIncome = section !== "liabilities";
    const showLiabilities = section !== "income";
    return <fieldset><legend>{showIncome && showLiabilities ? "הכנסות והתחייבויות" : showIncome ? "הכנסות" : "התחייבויות"}</legend>
      {showIncome && <div className="borrower-stack">{form.borrowers.map((borrower, index) => <section className="borrower-card" key={borrower.id ?? index}>
        <div className="borrower-card-heading"><div><span className="eyebrow">לווה {index + 1}</span><h3>הכנסות ותעסוקה — לווה {index + 1}</h3></div></div>
        <div className="responsive-form-grid">{select(index, "employmentType", "סוג תעסוקה", employmentTypeOptions)}{input(index, "employerName", "שם המעסיק או העסק", "שם המעסיק")}{input(index, "jobTitle", "תפקיד", "תפקיד נוכחי")}{input(index, "employmentSeniorityYears", "ותק בשנים", "0", "number")}{input(index, "monthlyNetIncome", "הכנסה חודשית נטו", "הזן סכום בש״ח", "number")}</div>
        <section className="additional-incomes-editor"><div className="borrower-card-heading"><div><span className="eyebrow">הכנסות נוספות</span><h4>הכנסות נוספות — לווה {index + 1}</h4></div><button type="button" className="secondary-action" onClick={() => onBorrowerChange(index, "additionalIncomes", [...borrower.additionalIncomes, emptyAdditionalIncomeForm()])}><Plus size={17} />הוספת הכנסה נוספת</button></div>
          {borrower.additionalIncomes.length === 0 ? <p className="empty-inline">לא נוספו הכנסות נוספות.</p> : borrower.additionalIncomes.map((income, incomeIndex) => { const incomeKey = `borrowers.${index}.additionalIncomes.${incomeIndex}`; const updateIncome = (field: "type" | "monthlyAmount" | "description", value: string) => onBorrowerChange(index, "additionalIncomes", borrower.additionalIncomes.map((item, itemIndex) => itemIndex === incomeIndex ? {...item, [field]: value} : item)); return <article className="additional-income-row" key={income.id ?? incomeIndex}><header><h5>הכנסה נוספת {incomeIndex + 1}</h5><button type="button" className="icon-text-button danger" onClick={() => onBorrowerChange(index, "additionalIncomes", borrower.additionalIncomes.filter((_, itemIndex) => itemIndex !== incomeIndex))}><Trash2 size={16} />מחיקה</button></header><div className="responsive-form-grid"><label className="form-field"><span>סוג הכנסה נוספת{requiredMark}</span><select value={income.type} onChange={(event) => updateIncome("type", event.target.value)}><option value="">בחירה</option>{additionalIncomeTypeOptions.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select>{errors[`${incomeKey}.type`] && <em role="alert">{errors[`${incomeKey}.type`]}</em>}</label><label className="form-field"><span>סכום הכנסה חודשי{requiredMark}</span><input type="number" min="0" step="0.01" inputMode="decimal" value={income.monthlyAmount} onKeyDown={(event) => preventInvalidNumericKey(event, false)} onChange={(event) => {if (isNonNegativeDecimalInput(event.target.value)) updateIncome("monthlyAmount", event.target.value);}} placeholder="הזן סכום בש״ח" />{errors[`${incomeKey}.monthlyAmount`] && <em role="alert">{errors[`${incomeKey}.monthlyAmount`]}</em>}</label>{income.type === "OTHER" && <label className="form-field"><span>תיאור ההכנסה{requiredMark}</span><input value={income.description} onChange={(event) => updateIncome("description", event.target.value)} placeholder="תאר את מקור ההכנסה" />{errors[`${incomeKey}.description`] && <em role="alert">{errors[`${incomeKey}.description`]}</em>}</label>}</div></article>;})}
        </section>
      </section>)}</div>}
      {showLiabilities && !usesHouseholdLiabilities(form.borrowerRelationship) && <div className="borrower-stack">{form.borrowers.map((borrower, index) => <div key={borrower.id ?? index}>{liabilitiesEditor(`התחייבויות — לווה ${index + 1}`, borrower.liabilities, `borrowers.${index}.liabilities`, (next) => onBorrowerChange(index, "liabilities", next))}</div>)}</div>}
      {showLiabilities && usesHouseholdLiabilities(form.borrowerRelationship) && liabilitiesEditor("התחייבויות משותפות למשק הבית", form.householdLiabilities, "householdLiabilities", (next) => onChange("householdLiabilities", next), "בתיק נשוי ההתחייבויות מוזנות פעם אחת עבור משק הבית.")}
    </fieldset>;
  }

  const showProperty = section !== "deal-details";
  const showDealDetails = section !== "property";
  return <fieldset><legend>{showProperty && showDealDetails ? "נכס ובקשת מימון" : showProperty ? "פרטי הנכס" : "פירוט עסקה"}</legend><div className="responsive-form-grid">{showProperty && <>{globalSelect("loanPurpose", "מטרת ההלוואה", loanPurposeOptions)}{globalSelect("propertyType", "סוג הנכס", propertyTypeOptions)}{form.propertyType === "OTHER" && globalInput("propertyTypeOtherDescription", "תיאור סוג הנכס", "תאר את סוג הנכס")}{globalInput("propertyCity", "עיר", "הקלד את עיר הנכס")}{globalInput("propertyAddress", "כתובת הנכס", "רחוב, מספר ועיר")}{globalInput("propertyValue", "שווי הנכס", "הזן סכום בש״ח", "number")}{globalInput("requestedAmount", "סכום המימון המבוקש", "הזן סכום בש״ח", "number")}</>}{showDealDetails && <label className="form-field form-field-wide"><span>פירוט עסקה{requiredMark}</span><textarea aria-label="פירוט עסקה" placeholder="פרט את מבנה העסקה, מטרת המימון, מידע חשוב והערות נוספות" rows={12} maxLength={5000} value={form.dealDetails} onChange={(event) => onChange("dealDetails", event.target.value)} aria-invalid={Boolean(errors.dealDetails)} />{errors.dealDetails && <em role="alert">{errors.dealDetails}</em>}</label>}</div></fieldset>;
}
