import { useCallback, useEffect, useState } from "react";
import { Download, Eye, FileCheck2, FileUp, Plus, RefreshCw, Trash2, X } from "lucide-react";
import type { ClientBorrower, DocumentRecord } from "../types";
import { api } from "../utils/apiClient";
import { formatDate, formatDocumentStatus, formatDocumentType, formatFileSize } from "../utils/formatters";

const borrowerRequirements = ["ID_FRONT", "ID_BACK", "ID_APPENDIX"] as const;
const clientRequirements = ["PROPERTY_RIGHTS", "POWER_OF_ATTORNEY"] as const;

export default function DocumentManager({clientId, borrowers, onUpdated}: {clientId: number; borrowers: ClientBorrower[]; onUpdated?: () => void}) {
  const [documents, setDocuments] = useState<DocumentRecord[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState<{name: string; url: string} | null>(null); const [otherOpen, setOtherOpen] = useState(false); const [otherFile, setOtherFile] = useState<File | null>(null); const [customTitle, setCustomTitle] = useState(""); const [description, setDescription] = useState(""); const [otherBorrowerId, setOtherBorrowerId] = useState("");
  const load = useCallback(async () => setDocuments(await api.documents(clientId)), [clientId]);
  useEffect(() => { void load(); }, [load]); useEffect(() => () => {if (preview) URL.revokeObjectURL(preview.url);}, [preview]);
  const complete = documents.filter((document) => ["UPLOADED", "VERIFIED", "REPLACED"].includes(document.status)); const requiredTotal = borrowers.length * borrowerRequirements.length + clientRequirements.length; const completedRequired = borrowers.reduce((sum, borrower) => sum + borrowerRequirements.filter((type) => complete.some((document) => document.borrowerId === borrower.id && document.documentType === type)).length, 0) + clientRequirements.filter((type) => complete.some((document) => document.borrowerId === null && document.documentType === type)).length;
  const upload = async (file: File | undefined, documentType: string, borrowerId: number | null, replacement?: DocumentRecord) => { if (!file) return; setBusy(true); setMessage(""); try { await api.uploadDocument(clientId, file, documentType, {borrowerId}); if (replacement) await api.deleteDocument(replacement.id); await load(); onUpdated?.(); setMessage(replacement ? "המסמך הוחלף בהצלחה." : "המסמך הועלה בהצלחה."); } catch { setMessage("העלאת המסמך נכשלה. ניתן להעלות PDF, PNG או JPG בלבד."); } finally {setBusy(false);} };
  const uploadOther = async () => { if (!otherFile || !customTitle.trim()) {setMessage("יש לבחור קובץ ולהזין שם או נושא למסמך."); return;} setBusy(true); try { await api.uploadDocument(clientId, otherFile, "OTHER", {borrowerId: otherBorrowerId ? Number(otherBorrowerId) : null, customTitle: customTitle.trim(), description: description.trim() || undefined}); await load(); onUpdated?.(); setOtherOpen(false); setOtherFile(null); setCustomTitle(""); setDescription(""); setOtherBorrowerId(""); setMessage("המסמך הנוסף הועלה בהצלחה."); } catch {setMessage("העלאת המסמך נכשלה.");} finally {setBusy(false);} };
  const download = async (document: DocumentRecord, show = false) => { try { const blob = await api.downloadDocument(document.id); const url = URL.createObjectURL(blob); if (show) setPreview({name: document.customTitle ?? document.originalFileName, url}); else {const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = document.originalFileName; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 30_000);} } catch {setMessage("לא ניתן לפתוח את המסמך כרגע.");} };
  const remove = async (document: DocumentRecord) => {if (!window.confirm(`למחוק את המסמך ${document.customTitle ?? document.originalFileName}?`)) return; setBusy(true); try {await api.deleteDocument(document.id); await load(); onUpdated?.(); setMessage("המסמך נמחק בהצלחה.");} catch {setMessage("מחיקת המסמך נכשלה.");} finally {setBusy(false);} };
  const row = (documentType: string, borrowerId: number | null) => {const document = complete.find((item) => item.documentType === documentType && item.borrowerId === borrowerId); const label = formatDocumentType(documentType); return <article className={`document-check-row${document ? " complete" : " missing"}`} key={`${borrowerId ?? "client"}-${documentType}`}><div className="document-title"><FileCheck2 /><div><h4>{label}</h4><p>{document ? formatDocumentStatus(document.status) : "חסר"}</p></div></div>{document ? <><div className="document-meta"><span>{formatDate(document.createdAt)}</span><span>{formatFileSize(document.sizeBytes)}</span></div><div className="document-actions"><button type="button" className="icon-text-button" onClick={() => void download(document, true)}><Eye size={16} />צפייה</button><button type="button" className="icon-text-button" onClick={() => void download(document)}><Download size={16} />הורדה</button><label className="icon-text-button"><RefreshCw size={16} />החלפה<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => void upload(event.target.files?.[0], documentType, borrowerId, document)} /></label><button type="button" className="icon-text-button danger" disabled={busy} onClick={() => void remove(document)}><Trash2 size={16} />מחיקה</button></div></> : <label className="secondary-action"><FileUp size={16} />העלאה<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => void upload(event.target.files?.[0], documentType, borrowerId)} /></label>}</article>;};
  const otherDocuments = documents.filter((document) => document.documentType === "OTHER");
  return <section className="documents-workspace"><div className="documents-progress"><div><strong>{completedRequired} מתוך {requiredTotal} מסמכי חובה הועלו</strong><span>{completedRequired === requiredTotal ? "כל מסמכי החובה קיימים" : "בתיק חסרים מסמכי חובה"}</span></div><div className="progress-track"><span style={{inlineSize: `${requiredTotal ? completedRequired / requiredTotal * 100 : 0}%`}} /></div></div>{message && <p className={message.includes("נכשלה") || message.includes("יש לבחור") ? "form-message error" : "form-message success"}>{message}</p>}
    <div className="document-checklist"><section><h3>מסמכי לווים</h3>{borrowers.map((borrower) => <article className="borrower-document-group" key={borrower.id}><h4>{borrower.isPrimary ? "לווה ראשי" : `לווה ${borrower.borrowerOrder}`} — {borrower.firstName} {borrower.lastName}</h4>{borrowerRequirements.map((type) => row(type, borrower.id))}</article>)}</section><section><h3>מסמכי תיק</h3>{clientRequirements.map((type) => row(type, null))}</section><section><div className="section-heading compact"><div><h3>מסמכים נוספים</h3><p>ניתן להעלות מספר בלתי מוגבל של מסמכים נוספים.</p></div><button type="button" className="secondary-action" onClick={() => setOtherOpen(true)}><Plus size={17} />הוספת מסמך נוסף</button></div>{otherDocuments.length === 0 ? <p className="empty-inline">לא הועלו מסמכים נוספים.</p> : <div className="documents-grid">{otherDocuments.map((document) => <article className="document-card" key={document.id}><div className="document-title"><h4>{document.customTitle}</h4><p>{document.description || formatDocumentType(document.documentType)}</p></div><div className="document-actions"><button type="button" onClick={() => void download(document, true)}>צפייה</button><button type="button" onClick={() => void download(document)}>הורדה</button><button type="button" onClick={() => void remove(document)}>מחיקה</button></div></article>)}</div>}</section></div>
    {otherOpen && <div className="modal-backdrop"><section className="modal content-card" role="dialog" aria-modal="true"><header className="modal-heading"><h2>הוספת מסמך נוסף</h2><button type="button" className="icon-action" onClick={() => setOtherOpen(false)}><X /></button></header><label className="form-field"><span>שם או נושא המסמך *</span><input value={customTitle} onChange={(event) => setCustomTitle(event.target.value)} placeholder="לדוגמה: שומת שמאי" /></label><label className="form-field"><span>תיאור</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="form-field"><span>שיוך ללווה</span><select value={otherBorrowerId} onChange={(event) => setOtherBorrowerId(event.target.value)}><option value="">מסמך ברמת התיק</option>{borrowers.map((borrower) => <option value={borrower.id} key={borrower.id}>לווה {borrower.borrowerOrder} — {borrower.firstName}</option>)}</select></label><label className="form-field"><span>קובץ *</span><input type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => setOtherFile(event.target.files?.[0] ?? null)} /></label><div className="modal-actions"><button type="button" className="secondary-action" onClick={() => setOtherOpen(false)}>ביטול</button><button type="button" className="primary-action" disabled={busy} onClick={() => void uploadOther()}>{busy ? "מעלה…" : "העלאה"}</button></div></section></div>}
    {preview && <div className="modal-backdrop"><section className="modal document-preview-modal content-card"><header className="modal-heading"><h2>{preview.name}</h2><button type="button" className="icon-action" onClick={() => setPreview(null)}><X /></button></header><iframe title={`תצוגת ${preview.name}`} src={preview.url} /></section></div>}
  </section>;
}
